logo = true
logoText = "å®‰é‚¦çš„åšå®¢"
logoType = "short" # long, short
description = "å®‰é‚¦çš„åšå®¢çš„æè¿°"
editBaseURL = "https://github.com/zzossig/zzoDocs/blob/master/content/en"
themeOptions = ["hacker","light","dark", "solarized","kimbie"]

useFaviconGenerator = true # https://www.favicon-generator.org/

wideViewAsDefault = false

enableWideBlogSwitch = true
enableTocSwitch = true
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = true
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/zzossig/hugo-theme-zzo"

enableComment = false
[utterances]       # https://utteranc.es/
  owner = "zzossig"              # Your GitHub ID
  repo = "zzoDocs"               # The repo to store comments

enableUiAnimation = true
enableAppbarSearchIcon = true
enableAppbarLangIcon = true
homeHeaderType = "text"
hideHomeHeaderWhenMobile = false
showMobileMenuTerms = ["tags", "categories", "series"]
enableGoToTop = true

enableWhoami = true

 

summaryShape = "classic"


searchResultPosition = "main"



archiveGroupByDate = "2006"


archivePaginate = 20


paginateWindow = 1



talksPaginate = 5


talksGroupByDate = "2006"



pubPaginate = 20


myname = "choi"



email = "example@gmail.com"


whoami = "ğŸ“šLearnerğŸ¤“NerdğŸŒWeb Developer"


bioImageUrl = "https://..."


useGravatar = false



location = "Seoul, Korea"


organization = "Hugo"


link = "https://zzossig.io"


enableBio = true


enableSidebar = true


enableSidebarTags = true


enableSidebarSeries = true


enableSidebarCategories = true


enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true


hideToc = false


tocFolding = true


tocPosition = "outer"


enableTocSwitch = true


itemsPerCategory = 5


sidebarPosition = "right"


showFeedLinks = true


showSocialLinks = true


enableThemeChange = true


googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""

enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true
updatePeriod = "monthly"

[socialOptions]
  email = "mailto:your@email.com"
[[share]]
  name = "facebook"
[[share]]
  name = "twitter"
  username = ""



